### ISSUE TITLE
v2020.1.117: Cannot create new project on Windows

### ISSUE THREAD

**Issue by madig** [CoatiSoftware/Sourcetrail#1001]
Steps to reproduce:
1. Create new project
2. Type some project name
3. Select some folder for the project location
4. Click "Add Source Group"

This results in an error popup saying "the specified location seems to be invalid. Please check the characters used in the path". I noticed that the path contains forward slashes as path separators, but changing them to backslashes does not fix the problem.

Using Windows 10 x64 1909, Sourcetrail v2020.1.117 x64. Works in v2019.4.102.

**Comment by egraether** [comment]
Does the path contain a period `.`?

**Comment by madig** [comment]
Yes, from my user name :O it werks if I chose a dotless path.

**Comment by assarbad** [comment]
Stumbled across the exact same issue also today. Initially I thought it was because I had junction points in the path, but it turned out the dot was the issue.

The annoying part was that I had been accessing it as `C:\work` and SourceTrail itself ended up "expanding" that path to `C:\Users\f.lastname\work`.

**Comment by mlangkabel** [comment]
Good news: The dot issue has already been fixed by merge of PR #959 and this will be part of the next release.

**Comment by adithyabsk** [comment]
For those who come across this issue before the next version goes out, here's a work around:
```console
$ ln -s [USERNAME_WITH_DOT] [USERNAME_WITHOUT_DOT]
```
Then simply use the symlink in sourcetrail
