### ISSUE TITLE
Indexing gets very slow with lots of exclude filters

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#1007]
A user reported that indexing gets very slow when lots of exclude filters are used in a source group.

Exclude filters are currently implemented using regexes (or chains of regexes) in FilePathFilter: https://github.com/CoatiSoftware/Sourcetrail/blob/master/src/lib/utility/file/FilePathFilter.cpp

This is probably really slow and needs to be profiled and replaced with a faster implementation.

**Comment by assarbad** [comment]
I didn't profile this, but a quick look at the code seems to suggest that the `regex` variable in each of the scopes in `FilePathFilter::convertFilterStringToRegex()` could be `static`, no? Not sure this would give much of an improvement, but it would certainly save construction, no?

Do you have examples of such "exclude filters". Does it refer to this?:

![exclude-filters-source-group](https://user-images.githubusercontent.com/3238620/81669707-dfb4a180-9446-11ea-85e5-3ed4f9a5cb35.png)

Suppose I'd want to look into this, where can I find entry-level material on how to get started? For example I never worked with Qt, but for this functionality it doesn't really seem relevant.

I'd probably also want to fix #1008 while at it.

**Comment by egraether** [comment]
Sure, you can give it a look! This is not a C++ code syntax problem. This has to be rethought. A regex can be incredibly slow when used wrong. I suppose the issue is caused by `*` and `**` wildcards, which can be checked beforehand. This needs to be rewritten to only do the minimum of work necessary.

**Comment by assarbad** [comment]
@egraether I'm familiar with regular expressions in various forms, not with this particular implementation, though. But I'll have a look anyway.

My current issue is how to get started with the build (the Wiki doesn't contain hints, nor does the `CONTRIBUTING.md` or `README.md`).

Either way, I'll use this ticket to take some notes regarding how to build. Maybe we can distill it into some more formal document later on.

**Comment by egraether** [comment]
It's in the [README](https://github.com/CoatiSoftware/Sourcetrail#how-to-build). That's all we have so far.

**Comment by Waqar144** [comment]
One other solution to this could be to write parsers for each of the statments instead of using regex. C++ regex(and is being considered for deprecation afaik) is inherently slow and there is not much that can be done here.

If we want to stick with regex, re2 is a much better option. Otherwise I would vote for custom parsers, they are more difficult to maintain, but are definitely a lot faster in my experience.

**Comment by assarbad** [comment]
@Waqar144 totally agree that another RE engine would likely be a _better_ choice, but RE may not be the best choice for the overall job. And even if RE are deemed to be _the_ solution, first it would probably be a good choice to make the existing ones less greedy (the last two are greedy right now).

However, what eludes me is the purpose of the code. I am very well capable of understanding the regular expressions, but I am unable to discern why they're there. It seems like idea is to take a shell-glob like pattern and translate that into a regex. However, the rules should be specified _somewhere_. Code isn't the place to specify the intent of the code, because code writers make mistakes.

So could one of the project members please help to nail down what the intent here is? It's definitely not POSIX shell globs nor Windows shell globs and either way it should be uniform across platforms for a cross-platform project. For example `[!...]` isn't covered as far as I can tell.

So what inputs do we accept and what wildcards are expected to match what? We need exact rules.

Raw string literals (`LR"..."`) could (or rather _would_) make the regular expressions somewhat more readable:

``` c++
{
    std::wregex regex(LR"([^\\])([^/])([\]])");
    regexFilterString = std::regex_replace(regexFilterString, regex, LR"$1$2[\]]");
}

{
    std::wregex regex(LR"([\[])([^\\])");
    regexFilterString = std::regex_replace(regexFilterString, regex, LR"[\[]$2");
}
```

Those are apparently meant to sidestep issues with the very first RE (`LR"[\\/]"`).

Those two RE are then followed by no less than **nine** REs used to escape _single_ RE special characters. And only then comes the translation of `**` and `*` as "glob" wildcards.

Going by the implementation and assuming that this declares the intent and ignoring the possibility that the implementer included a glitch or I misunderstood something, the current rules seem to be:

* for every literal slash or backslash, match either
* for every `**` match _anything_ (`.`) greedily
* for every backslash _or_ asterisk (why???) match any number of slashes or backslashes (including none) greedily

... that's the verbal description of the first and the two last rules. The remainder in the middle basically is used to escape the RE syntax issues.

The last RE is a bit puzzling, too, as you will have noticed from the verbal description. I am wondering whether the intent was rather to match any number of backslashes?:

``` c++
{
    std::wregex regex(L"[\\*]");
    regexFilterString = std::regex_replace(regexFilterString, regex, L"[^\\\\/]*");
}
```

Either way, if we assumed that it should have been `L"[\\]*"` I still wonder why it only covers backslash as input.

**Comment by mlangkabel** [comment]
I think that the intention of this code was to convert all "special" characters that are entered as file path filter by the user to their regex pattern. So
```cpp
{
	std::wregex regex(L"[\\+]");
	regexFilterString = std::regex_replace(regexFilterString, regex, L"[\\+]");
}
```
will convert the user-specified file path filter string `foo+bar.h` to the regex `foo[\+]bar.h` which will later be used to match against all potential files to index. This regex will match the input string "foo+bar.h", wich is exactly what the user wanted.
The 'convertFilterStringToRegex()' method is only called once per filter string, and those strings are usually quite short. So we didn't assume that this conversion would be a performance issue.

The rules that should have been implemented by this conversion to a regex are
* match every character (including all special characters an regex escape characters) entered by the user exactly
* for every literal slash or backslash, match either because this should be platform independent (a Sourcetrail project created on Windows should still be working on Linux).
* The `*`character in the input shall match any sequence of characters, except `\` or `/`. This should be used to stay in the same hierarchy level of the file system and not  recurse into sub directries ("src/*/test.h"should match "src/app/test.h" but not "src/app/widget/test.h").
* The `**`character sequence should match anything ("src**test.h"should match "src/app/test.h" and also "src/app/widget/test.h").

**Comment by egraether** [comment]
I did a little investigation today and my results are:

* The time-consuming regexes for `*` or `**` do cause a slowdown of about 10 to 20x, but they are only applied when necessary.

* In the standard use-case the main issue is the string conversion in [FilePathFilter::isMatching()](https://github.com/CoatiSoftware/Sourcetrail/blob/078feca0044f48d0a18685cfb83a1e21085d0f74/src/lib/utility/file/FilePathFilter.cpp#L15), which takes around 66% of the execution time.

I was not aware that `FilePath::wstr()` is taking that much time. We need to make sure it is only converted once before testing all `FilePathFilters`. Or we might even move the match method into FilePath as `bool FilePath::isMatching(std::wregex)`, so it can access the underlying string directly.

**Comment by egraether** [comment]
I continued my investigation and found that [FilePathFilter::isMatching()](https://github.com/CoatiSoftware/Sourcetrail/blob/078feca0044f48d0a18685cfb83a1e21085d0f74/src/lib/utility/file/FilePathFilter.cpp#L15) is only half the story.

When indexing a project the exclude filters are prepared by [SourceGroupSettingsWithExcludeFilters::getFiltersExpandedAndAbsolute()](https://github.com/CoatiSoftware/Sourcetrail/blob/b7ad802cc21b231d8012fa46bd68c4a42725b9e0/src/lib/settings/source_group/component/SourceGroupSettingsWithExcludeFilters.cpp#L44), which converts exclude filters into the form `<project_path>/<exclude_filter>**` in the standard use-case.

I thought I could achieve a performance gain by separating the `project_path` check from the rest and doing it only once for all exclude filters. In practice I couldn't measure a performance gain. This was probably due to the introduction of other string operations. Maybe this could have been done better using `std::string_view`.

Anyhow, I could approximately double the performance of the exclude filters by doing the `FilePath::wstr()` conversion only once and other slight improvements with #1030. But I'm still convinced that there is a way to improve this far more, so I'm leaving this open.
