### ISSUE TITLE
Using sourcetrail from within a docker container

### ISSUE THREAD

**Issue by GitHimanshuc** [CoatiSoftware/Sourcetrail#1067]
Is there a way to use sourcetrail to inspect a code being that has to compiled inside a docker container? 

The location of the source files is outside the container but due to very complex dependencies the compilation should be done inside the docker container.

## What I was able to do
I was able to get the compilation data file using the cmake which I used to make a project file using the GUI. Is there any way to do this using the command line only?

But, once the project is created the indexing fails. This is kind of expected as the location of files in the database file will have paths according to the docker container.

**So, is there some way to create all the required files using the command line inside the container but visualize it outside using the GUI?**

I tried this inside the container but it got stuck:
```
sourcetrail index --full --project-file ../spectre/sourcetrail/spectre.srctrlprj
```
![image](https://user-images.githubusercontent.com/37404148/90623286-e9168c80-e233-11ea-83ed-ee0535575201.png)

**Comment by mlangkabel** [comment]
Hey, yes, this should be possible. 
You should be able to create a `.srctrlprj` that uses all the paths as they are supposed to be on the docker container. For this step, maybe create the project using the Sourcetrail GUI (if it complains about non-existing paths, ignore that, because you won't run the indexer on that system anyways).

Then, copy that file into your docker container and you should be able to execute the command you already posted.

After indexing is done, there should be a `.srctrldb` file next to the `.srctrlprj` file on the docker container. Copy both of these files to your other system and you should be able to view the indexed project there (btw, this is how we ship our pre-indexed sample projects and the tutorial that come with the application).
