### ISSUE TITLE
Linux: Python environment error results in not able to index any python projects

### ISSUE THREAD

**Issue by ttang852** [CoatiSoftware/Sourcetrail#1129]
Can't index any python project and getting the error message of "An error occurred while checking environment path. Unable to check validity". This problem appears in Centos 7 for both version 2020_2_43 and 2020_4_35. However for Ubuntu 18.04.5, the version 2020_2_43 has no problem but the newer version 2020_4_35 stop to work.

**Comment by Gansgar** [comment]
Are you able to index your projects or are you getting 255 errors when doing a full reindex?

If so, you've the same problem I've hit upon and mentioned here: https://github.com/CoatiSoftware/SourcetrailPythonIndexer/issues/13#issuecomment-759825919

**Comment by ttang852** [comment]
On Ubuntu 18.04.5 with Sourcetrail 2020_4_35, I cannot index the python project at all and keep getting tons of "returned code "255" with message "File not found or resource error occurred". But, Sourcetrail 2020_2_43 has no problem. For Centos 7, both versions don't work.

**Comment by dkasak** [comment]
I'm getting the same thing on Arch Linux with 2020.4.35.

**Comment by lucsch** [comment]
I'm getting the same on OSX with 2020.4.35

**Comment by hasturkun** [comment]
I'm having what might be the same issue, using SourceTrail 2020.4.35 running on Ubuntu 16.04.7.
Running SourcetrailPythonIndexer manually gives the following error message:

> [4799] Error loading Python lib '/tmp/.mount_SourceRdchT0/usr/share/data/python/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_SourceRdchT0/usr/share/data/python/libpython3.6m.so.1.0)

**Comment by mlangkabel** [comment]
I am not seeing this issue on Windows, thanks to the comment of @Gansgar on [CoatiSoftware/SourcetrailPythonIndexer#13](https://github.com/CoatiSoftware/SourcetrailPythonIndexer/issues/13#issuecomment-759825919) I believe I can imagine the root of this issue.

With PR #1107 we switched to the new version of QProcess::start() where command and args are passed as different parameters instead of using just one string. However, our Python indexer commands still only provide everything as one string and pass it in as "command". Seems to be fine for Windows, but cause issues on OSX and Linux.

Will start working on the fix that splits command and args now!

**Comment by ttang852** [comment]
Thank you for looking into the issue!

-Thomas

**Comment by neal-hu-chn** [comment]
![image](https://user-images.githubusercontent.com/63115566/106381073-52a8e280-63f1-11eb-819e-890b39930caa.png)
another bad experience！

**Comment by sprine** [comment]
I was running into the same issues @neal-hu-chn, and wrote a simple [script](https://gist.github.com/sprine/c3f8995121774bc23fec29daa8a91367) to index the files and open sourcetrail at the end. This might be good enough while waiting for the proper fix to land. The script can be run in the Terminal by calling `./sourceindex.sh` and it indexes all Python files in the current path.

**Comment by nealhuchn** [comment]
> I was running into the same issues @neal-hu-chn, and wrote a simple [script](https://gist.github.com/sprine/c3f8995121774bc23fec29daa8a91367) to index the files and open sourcetrail at the end. This might be good enough while waiting for the proper fix to land. The script can be run in the Terminal by calling `./sourceindex.sh` and it indexes all Python files in the current path.

thanks  alot buddy

**Comment by mlangkabel** [comment]
Small update: I've done a lot of testing during the last days and it looks like the issue is caused by our docker images that are used to build the release. Maybe it is the fact that the Linux images have been built on a Windows host. I've set up a Linux infrastructure now and will try to rebuild those images on a Linux host to see if that helps.

**Comment by ttang852** [comment]
Thanks for digging into the problem and the update. Appreciate it!

-Thomas

**Comment by nealhuchn** [comment]
> Small update: I've done a lot of testing during the last days and it looks like the issue is caused by our docker images that are used to build the release. Maybe it is the fact that the Linux images have been built on a Windows host. I've set up a Linux infrastructure now and will try to rebuild those images on a Linux host to see if that helps.

grate to you

**Comment by mlangkabel** [comment]
Found out that the docker images are probably not the issue. The issue is the change in Pull Request #1107. On my Ubuntu test system I get the same errors as you, but after reverting the PR on the master, triggering a docker build (with the new docker images) and running the Python indexer, it all works fine. Even though it seems to be fixed, I'd like to continue investigating a little.

**Comment by ttang852** [comment]
Thanks for the update! Looks like we are seeing light at the end of the
tunnel! Thanks!

-Thomas

**Comment by mlangkabel** [comment]
So it seems the reason for this was a wrong call to QProcess::start(). We have been planning to switch to boost process for quite a while and I'm almost done preparing the pull request. For this change I tested every invocation of external processes by Sourcetrail on my Linux system and it looks very promising. So that PR will probably make it into the next beta release. If it causes issues for you, we can still think about reverting that PR and using the current version for the release (roughly 2 weeks after beta).

**Comment by mlangkabel** [comment]
Done with merge of Pull request #1145
