### ISSUE TITLE
Is there a plan to support SQL？

### ISSUE THREAD

**Issue by partoneplay** [CoatiSoftware/Sourcetrail#1147]
SQL sometimes can be very complicated. And [ANTLR](https://github.com/antlr/antlr4) is a good tool for analyzing SQL.

**Comment by partoneplay** [comment]
Ok. I found 'Sourcetrail Language Extension Guide'.

**Comment by mlangkabel** [comment]
SourcetrailDB can be used to store data to a `.srctrldb` file, readable by Sourcetrail. It is available in C++ and there are bindings for C#, Java, Python and Perl. So if anyone writes an indexer tool in any of those languages and the call to that tool takes the path to the (SQL) file to index and a path to the output database, Sourcetrail should be able to cope with it :)

**Comment by partoneplay** [comment]
I use Java and [ANTLR](https://github.com/antlr/antlr4) to parse SQL.
In the release jar file, `SymbolKind` class is final and the constructor is private, but I want my own symbol kind  for SQL(Like: Table、Column)
Do i have to modify `SourcetrailDB/core/src/SymbolKind.cpp` and do my own Java Bindings? 
Sorry for my bad  English.
[sourcetrailbd_java_v4_db25_p0-windows-64bit.zip](https://github.com/CoatiSoftware/SourcetrailDB/releases/download/v4.db25.p0/sourcetrailbd_java_v4_db25_p0-windows-64bit.zip)

**Comment by mlangkabel** [comment]
Currently the SymbolKinds that Sourcetrail supports are limited to the selection that is offered by SourcetrailDB, because Sourcetrail also needs to implement some logic for each symbol kind (e.g. how to display it in the graph and code view). We are planning on letting everyone define own symbol kinds, but we didn't get this done, yet.

So for now, I would suggest to just use the symbol kinds that are available (maybe `Class` for `Table` and `Field` for `Column`). Once you have a working prototype, we will either add new symbol kinds to Sourcetrail and SourcetrailDB or we will have a mechanism that lets you define your own. 

Don't let this stop you :)

**Comment by partoneplay** [comment]
Thanks a lot.
