### ISSUE TITLE
Rename "Edit Project" menu action to "Project Properties"

### ISSUE THREAD

**Issue by Mike4Online** [CoatiSoftware/Sourcetrail#170]
Setting "Preferences" is done via the "Help" menu, but this is non-standard.  Preferences should be set from either the Edit menu, or from a Tools menu.

The "To overview" menu pick on the Edit menu should probably be moved to the View menu, as picking this option changes the view (it does not edit anything).

The "Edit Project" menu pick on the "Project" menu should probably be renamed Project Properties.  You would expect "edit" picks to be on the Edit menu, so it would be best to leave this where it is and rename it.

**Comment by mlangkabel** [comment]
Hi @Mike4Online. Those are really good suggestions! Thanks for reporting them.
1. This will be fixed in today's release.
2. I think we added the "To overview" option to the edit menu because right now all other code navigation related options are there, too. And I think those code navigation options are there because the "find" option usually can be found there. Do you think we should introduce a "navigation" menu?
3. I really like that idea. Everytime I'm looking for the Edit Project button I first click the Edit menu ;)

**Comment by Mike4Online** [comment]
Malte,

Thanks for the quick response.

>> 1. This will be fixed in today's release.

Great.

>> 2. I think we added the "To overview" option to the edit menu because
right now all other code navigation related options are there, too. And I
think those code navigation options are there because the "find" option
usually can be found there. Do you think we should introduce a "navigation"
menu?

Now that I have considered what you've written, you're probably right to
leave navigation on the Edit menu.

>> 3. I really like that idea.

Glad I could contribute.  I posted two other "Issues" in the issue tracker
as well.

- Michael Litwak (Mike4Online)

**Comment by egraether** [comment]
Sourcetrail users have become used to this naming convention and it hasn't come up again.
