### ISSUE TITLE
Support HJKL controls in graph

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#210]

**Comment by phonetagger** [comment]
Would be nice to have this in the source code window as well. Also support half-page and full-page up/down navigation as well (CTRL+U, CTRL+D, CTRL+B, CTRL+F, respectively). And having vim-like search (/ and ?) would be really nice too! (While we're at it, what about having a full-blown editor? Or maybe just omit the code pane entirely, and anytime you click on the graph, instead of locating it in the code pane, instead, locate it in the separate linked IDE window! Of course some people would really not like that option, but it might be pretty cool.)

**Comment by egraether** [comment]
Fixed with #935
