### ISSUE TITLE
conda support?

### ISSUE THREAD

**Issue by BlurryLight** [CoatiSoftware/Sourcetrail#747]
Hey, I'm trying to apply Sourcetrail on a pytorch project to help me understand but failed. 
My environment is :
OS: Manjaro 18.1.12 X64
Python:  default 3.74 with jedi 0.15, 
               anaconda python is 3.73 with jedi

Sourcetrail keeps warning the envs is not valid , and during the indexing , Sourcetrail cannot index some symbol from libraries in virtual envs. 

Does it support conda env now?  or I have missed something to do?
![image](https://user-images.githubusercontent.com/14940338/68390182-b1a48b00-019f-11ea-9575-504bf7e3bea9.png)

**Comment by mlangkabel** [comment]
Thank you very much for reporting. 

As this issue is fully within the scope of the Python indexer, we should continue disucssing it over at https://github.com/CoatiSoftware/SourcetrailPythonIndexer/issues/59.

If you think that the issue you are reporting is a different one, please feel free to re-open this issue.
