### ISSUE TITLE
`-std=c++` cannot be used with c sources

### ISSUE THREAD

**Issue by timblechmann** [CoatiSoftware/Sourcetrail#937]
i have a project where some `foo.c` files are forced to be compiled as c++ (by specifying `-std=c++`). therefore i'm having 2 related parser errors:

* `invalid argument "-std=c++" not allowed with "C"`
* `cannot use "try" with exception disabled`, probably because the file is parsed as c, not as c++

**Comment by mlangkabel** [comment]
Hi @timblechmann, which version of Sourcetrail are you using? And how did you set up your project? Did you start from an empty sourcgroup? Or use a compilation database?

**Comment by timblechmann** [comment]
i'm on `2019.4.61`. i was using a cmake-exported compile database, the source files were set up via:
```
set_source_files_properties(foo.c PROPERTIES LANGUAGE CXX)
```

**Comment by mlangkabel** [comment]
Ok, so it looks to me like the error above (which is reported by the clang compiler that is used by Sourcetrail) is correct behavior. 

Is there a reason why you need to declare your C files inside your CMakeLists file as CXX? Can't you change it to `set_source_files_properties(foo.c PROPERTIES LANGUAGE C)`?

**Comment by timblechmann** [comment]
> Is there a reason why you need to declare your C files inside your CMakeLists file as CXX?

well, it's a codebase that evolved over 30+ years. some of the files are compiled with different languages on different platforms (e.g. some files with `.c` extension need to be compiled as c++ or objective c++, some `.m` files have to compiled as obj c++).

----

of course it's architecturally cleaner to rely on the extension, but i've seen lots of code where the build system forces specific files to be compiled with a different language

**Comment by mlangkabel** [comment]
Ok, to me it doesnt look like Sourcetrail is doing anything wrong. It just does what the build config (that has been generated from cmake) tells it to do. As a workaround, you could 
* duplicate the source group, 
* remove the ".c" file extension from the first sourcegroup
* add "-xc++" to the list of compiler flags of the first sourcegroup
* remove everything but the ".c" file extension from the second sourcegroup
* add "-xc" to the list of compiler flags of the second sourcegroup

**Comment by cj-obrien** [comment]
@mlangkabel 

I have a related issue. I am trying to use Sourcetrail to index a codebase supplied by an external vendor and some of the C++ source files use a .c extension.

I was hoping by following your suggestion above and adding "-xc++" to the list of compiler flags I could convince Sourcetrail/Clang to ignore the file extension, but I still see the following errors:

`invalid argument "-std=gnu++14" not allowed with "C"`

It appears the the "-xc++" compiler flag has no effect. Any tips on how to proceed?

**Comment by timblechmann** [comment]
> I have a related issue

it's actually the same issue

**Comment by mlangkabel** [comment]
Sourcetrail will also tell you the file that caused this error. So try to pinpoint it by only indexing that single file. Maybe clang still gets confused by the file extension. If it is a .c file, try renaming it to .cpp and check if that helps. But maybe it is caused by the contents of that file. Just go through it and check if there is anything in that file that implies a C language standard.

**Comment by timblechmann** [comment]
@mlangkabel can you confirm that sourcetrail uses `-xc++` to override the language that is used for parsing the file?

**Comment by mlangkabel** [comment]
Yes, it is added here: https://github.com/CoatiSoftware/Sourcetrail/blob/master/src/lib_cxx/project/SourceGroupCxxEmpty.cpp#L211

However, Clang always uses the latest occurrence of an argument and ignores all previous values that have been set. Sourcetrail adds the `-xc++` argument __BEFORE__ adding all the arguments that have been provided by the user, in order to give the user the chance to override the default behavior.

So if your source groups is an "Empty C++ Source Group" but explicitly sets a different language, then that different language will be used.

**Comment by timblechmann** [comment]
> So if your source groups is an "Empty C++ Source Group" but explicitly sets a different language, then that different language will be used.

well, i'm using the compile database generated by cmake. my flags compile the file with `-xc++ -std=c++`, but sourcetrail reports `-std=c++`. maybe clang takes the first occurrence of `-x`
